-- Generated by psc-make version 0.6.9.3
module Data.Foreign.Keys where
import Data.Foreign ()
import Prelude ()
import Data.Foreign.Keys ()
import Prim ()
import Prelude ()
import Data.Either ()
import Data.Foreign ()
import Data.Function ()
foreign import keys :: Data.Foreign.Foreign -> Data.Foreign.F [Prim.String]
