-- Generated by psc-make version 0.6.9.3
module Data.Foreign.Null where
import Data.Foreign ()
import Prelude ()
import Prim ()
import Prelude ()
import Data.Maybe ()
import Data.Either ()
import Data.Foreign ()
newtype Null (a :: *) = Null (Data.Maybe.Maybe a)
foreign import readNull :: forall a. (Data.Foreign.Foreign -> Data.Foreign.F a) -> Data.Foreign.Foreign -> Data.Foreign.F (Data.Foreign.Null.Null a)
foreign import runNull :: forall a. Data.Foreign.Null.Null a -> Data.Maybe.Maybe a
