-- Generated by psc-make version 0.6.9.3
module Main where
import Prelude ()
import Control.Monad.Eff.Confirm ()
import Debug.Trace ()
import Prim ()
import Prelude ()
import Debug.Trace ()
import Control.Monad.Eff.Confirm ()
import Control.Monad.Eff ()
foreign import main :: Control.Monad.Eff.Eff (confirm :: Control.Monad.Eff.Confirm.Confirm, trace :: Debug.Trace.Trace) Prelude.Unit
